api_version: aster.dev/v1alpha2
kind: Package

metadata:
  name: aster-docs
  version: 0.2.0-alpha.1
  license: Apache-2.0

spec:
  build:
    system: npm
  exports:
    documentation:
      path: docs
  dependencies: []
