api_version: aster.dev/v1alpha1
kind: Package

metadata:
  name: aster-docs
  version: 0.1.0-dev
  license: Apache-2.0

spec:
  build:
    system: npm
  exports:
    documentation:
      path: docs
  dependencies: []
